### ISSUE TITLE
Api\.local-chromium\download-Win64-706915.zip' because it is being used by another process.

### ISSUE THREAD

**Issue by Priyank-Kotiyal** [hardkoded/puppeteer-sharp#1622]
### Description
Getting error 'download-Win64-706915.zip' because it is being used by another process' at BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision).

### Complete minimal example reproducing the issue

`await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                //ExecutablePath = "C:/Program Files/Google/Chrome/Application"
            });
            using (var page = await browser.NewPageAsync())
            {
                await page.SetContentAsync(htmlContent);
                var result = await page.GetContentAsync();
                await page.PdfAsync("a.pdf");
            }`

### Expected behavior:

Should download chromium and work fine.

### Actual behavior:

Getting error zip is used by another process at DownloadAsync().

### Versions

2.0.4 for .net core app.

### Additional Information

Checked by passing executable path to chrome as well but not working. Also how it will work in linux server? As I am using app on local windows for development but I deploy app on linux using docker images.

**Comment by Androbin** [comment]
> * **NOTE** BrowserFetcher is not designed to work concurrently with other
> * instances of BrowserFetcher that share the same downloads directory.

**Comment by kblok** [comment]
Can you share the stack trace?

**Comment by madebypomelo** [comment]
I was facing the same issue in my .NET Core 3.1 application.
It seems that the browserFetcher starts downloading Chrome as a Zip file, but then fails after creating the empty zipfile.
Running `var browserFetcher = new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision).Result;` instead of `await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);` worked for me. I don't have my project in production yet, so I will investigate this behavior later on - but for now, the most important thing is that I'm able to test my code 😄 

I have no clue why this is happening. It worked on my PC some days ago, but after a clean Windows 10 reinstall, I was facing this issue too.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by ttool22** [comment]
I also have this problem, I have the latest version of puppeteer and I have this error 
local-chromium\chrome-win.zip' because it is being used by another process.
