### ISSUE TITLE
How to force PuppeteerSharp go to next page after current page timeout.

### ISSUE THREAD

**Issue by zydjohnHotmail** [hardkoded/puppeteer-sharp#1792]
Hello:
I am now using PuppeteerSharp version 5.0.0 on Windows 10.
Now, I found this issue: when I use Chrome by hand to visit some web sites, 99% of the times, the page will show without issue, for about 1% of the time, the web page is down, then I can’t visit the web page.  It is normal.
But when I use PuppeteerSharp to visit some web sites, quite often, the page has never finished loading, then I got Navigation Timeout error.
However, since I have a lot of pages under one domain to visit.
I want to know if I can simply let those pages timeout, like after 30 seconds, then let PuppeteerSharp ignore the timeout error, and visit next page.
Some web sites seem to be able to detect PuppeteerSharp, so the accept cookie page never show up, but the accept cookie page shows up immediately if I visit it by hand to launch Google chrome.
Thanks,

**Comment by kgar** [comment]
I have experienced similar issues with some websites. There are anti-bot measures that some websites use which can rate-limit or otherwise cause the website not to function normally when using automation software on a browser.

You can wrap the individual page visits in try/catch blocks in order to ignore the timeout error and move to the next page in your workflow. This is something that PuppeteerSharp probably should not do automatically, because some users will want to know that a page timed out when attempting to load. However, there are things you can try to improve your chances.

You can try to use stealth techniques, such as those found in [this PuppeteerSharp extras repo](https://github.com/Overmiind/Puppeteer-sharp-extra).

Also, I have found that, in some cases, updating your User Agent String to remove the word "Headless" actually makes some websites work.

Have you tried running the PuppeteerSharp session in both headless and headful modes to see if the results are different?

Have you also tried increasing the timeout on `[GoToAsync}(https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_GoToAsync_System_String_PuppeteerSharp_NavigationOptions_)`?

**Comment by kblok** [comment]
To keep the repo organized let's leave Github issues for Feature Requests, bugs and issues.
I kindly ask you to create a question on Stack Overflow. I follow the tag [puppeteer-sharp](https://stackoverflow.com/questions/tagged/puppeteer-sharp). This will help us get more eyes on those questions and leave answers easily available to the community.
Feel free to paste the Stack Overflow link here.
