### ISSUE TITLE
Migrate from AppVeyor to Github actions

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#1836]
It would be great if we could get out of appveyor.

**Comment by kgar** [comment]
I'm starting my study of Github Actions right now.

Do you have a preference on how the new setup should work?

**Comment by venky8951** [comment]
Hi @kblok
I Have been working on GitHub Actions for a while in my organization can I pick this up ?
I have tried out Appveyor's Linux CI and was able to build you can checkout in my forked [repo](https://github.com/venky8951/puppeteer-sharp/actions) it fails for dotnet test I'm not really sure why any help is appreciated 

If I can resolve this I would like to Migrate AppVeyor's Demo project as well to GitHub Actions

**Comment by kblok** [comment]
Sure you can!

**Comment by kblok** [comment]
@venky8951 our tests are now on net 6 :)

**Comment by venky8951** [comment]
Hi @kblok I have completed migrating Demo and linux appveyor files in .NET 6 -> [Actions](https://github.com/venky8951/puppeteer-sharp/actions)
but while running tests you can see it fails 7 initially and then in next iteration it passes, any suggestions (are these long running tests and we need to configure some time ?) here is the logs -> https://github.com/venky8951/puppeteer-sharp/runs/4813258463?check_suite_focus=true

**Comment by kblok** [comment]
@venky8951 are you setting up the SSL certificate?

**Comment by venky8951** [comment]
> @venky8951 are you setting up the SSL certificate?

Yes Im doing it while Installing Dependencies -> (       [ dotnet dev-certs https -ep lib/PuppeteerSharp.TestServer/testCert.cer](https://github.com/venky8951/puppeteer-sharp/blob/d598bacdf2a17023d4eb7efac7dffc5953cbef3c/.github/workflows/dotnet.yml#L34))

**Comment by kblok** [comment]
Let's force `-f net6.0` on linux :)

**Comment by venky8951** [comment]
> Let's force `-f net6.0` on linux :)

Thank you! this seem to be working but one test fails due to this stack trace 
`at PuppeteerSharp.Tests.CoverageTests.JSCoverageTests.ShouldReportScriptsThatHaveNoCoverage() in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs:line 129`

Here are results ->https://github.com/venky8951/puppeteer-sharp/runs/4818304083?check_suite_focus=true

if its okay I can create a PR? ,my fork is 60+ commits ahead ;) (Due to the fact the we need to test these actions on GitHub itself) hope that wont create problems and gets resolved in squash as it happened last time

**Comment by kblok** [comment]
Yeah. Let's create a PR :)
