### ISSUE TITLE
Browser TaskQueue is disposed when Page closed/disposed

### ISSUE THREAD

**Issue by gabmilg** [hardkoded/puppeteer-sharp#1878]
### Description
It's is more a questions than an issue.

I'm trying to reuse browser instance , the problem is that when first page is disposed the `TaskQueue `of the browser instance disposed as well as a result making screenshots is impossible for the next created page of the same browser instance ->
it's throws `the semaphore has been disposed` exception.

I wonder if it's an intended behavior ?

Thanks!

### Versions

* PuppeteerSharp 6.0.0
* .NET 5.

**Comment by kblok** [comment]
It's quite hard to get the idea with no code example.

**Comment by diegoful** [comment]
The page should not dispose `_screenshotTaskQueue` in `DisposeAsync()`, since it's an object passed by the `Browser`. Disposing `_screenshotTaskQueue` marks `Browser.ScreenshotTaskQueue` as disposed, preventing reusing it for other pages. 

**Proposed fixed**

Current code in Page.cs:2589:
`        public ValueTask DisposeAsync() => new ValueTask(CloseAsync()
            .ContinueWith(
                _ => _screenshotTaskQueue.DisposeAsync(),
                TaskScheduler.Default));
`
Should be:

`
public ValueTask DisposeAsync() => new ValueTask(CloseAsync());
`

**Comment by kblok** [comment]
PRs are welcome!

**Comment by jpeirson** [comment]
I was also having this problem with 6.0.0. This should be fixed in PR #1880 .

**Comment by qstarin** [comment]
Any chance of a point release to push this out? I'm blocked from updating to v6 due to this error.

**Comment by kblok** [comment]
@qstarin I can push a version tomorrow.
