### ISSUE TITLE
How to export an untagged PDF?

### ISSUE THREAD

**Issue by heku** [hardkoded/puppeteer-sharp#1958]
Hi,

I also posted this question to https://github.com/microsoft/playwright/issues/13917, I confirmed the problem also exist in PuppeteerSharp as well.

I tried the `ignoreDefaultArgs : ['--export-tagged-pdf']` argument metioned in https://github.com/puppeteer/puppeteer/issues/8100, but not work.
```cs
            using var downloader = new PuppeteerSharp.BrowserFetcher();
            var reversion = await downloader.DownloadAsync();
            var chrome = await PuppeteerSharp.Puppeteer.LaunchAsync(new PuppeteerSharp.LaunchOptions
            {
                Headless = true,
                ExecutablePath = reversion.ExecutablePath,
                IgnoredDefaultArgs = new[] { "--export-tagged-pdf" },
                IgnoreHTTPSErrors = true,
                DefaultViewport = null // fullscreen
            }); ;

            var page = await chrome.NewPageAsync();
            await page.GoToAsync(URL);
            await page.PdfAsync("puppeteer_7_0_latest.pdf");
```

So, do you know how to export an untagged PDF via PuppetterSharp?

**Comment by kblok** [comment]
Puppeteer-Sharp relies heavily on Chromium features.
Some bugs are caused by puppeteer, but others can be caused by chromium.
This sounds like a chromium issue. You can report those issues [here](https://bugs.chromium.org/p/chromium/issues/list).

I saw that it was reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1309963).

**Comment by heku** [comment]
Thx @kblok , I'd got response from playwright thread, and seems this is upstream Chromium issue.
